
const keys = {
    a: 'keyboard.a',
    b: 'keyboard.b',
    c: 'keyboard.c',
    d: 'keyboard.d',
    e: 'keyboard.e',
    f: 'keyboard.f',
    g: 'keyboard.g',
    h: 'keyboard.h',
    i: 'keyboard.i',
    j: 'keyboard.j',
    k: 'keyboard.k',
    l: 'keyboard.l',
    m: 'keyboard.m',
    n: 'keyboard.n',
    o: 'keyboard.o',
    p: 'keyboard.p',
    q: 'keyboard.q',
    r: 'keyboard.r',
    s: 'keyboard.s',
    t: 'keyboard.t',
    u: 'keyboard.u',
    v: 'keyboard.v',
    w: 'keyboard.w',
    x: 'keyboard.x',
    y: 'keyboard.y',
    z: 'keyboard.z',
    //大键盘0-9
    0: 'keyboard.key0',
    1: 'keyboard.key1',
    2: 'keyboard.key2',
    3: 'keyboard.key3',
    4: 'keyboard.key4',
    5: 'keyboard.key5',
    6: 'keyboard.key6',
    7: 'keyboard.key7',
    8: 'keyboard.key8',
    9: 'keyboard.key9',
    //小键盘0-9
    num0: 'keyboard.num0',
    num1: 'keyboard.num1',
    num2: 'keyboard.num2',
    num3: 'keyboard.num3',
    num4: 'keyboard.num4',
    num5: 'keyboard.num5',
    num6: 'keyboard.num6',
    num7: 'keyboard.num7',
    num8: 'keyboard.num8',
    num9: 'keyboard.num9',
    //小键盘+ - * / . enter
    'num+': 'keyboard.numplus',
    'num-': 'keyboard.numminus',
    'num*': 'keyboard.nummultiply',
    'num/': 'keyboard.numslash',
    'num.': 'keyboard.numperiod',
    numenter: 'keyboard.numenter',
    //上下左右箭头
    up: 'keyboard.uarrow',
    down: 'keyboard.darrow',
    left: 'keyboard.larrow',
    right: 'keyboard.rarrow',
    //功能键
    space: 'keyboard.space',
    enter: 'keyboard.enter',
    pgup: 'keyboard.pgup',
    pgdn: 'keyboard.pgdn',
    home: 'keyboard.home',
    end: 'keyboard.end',
    insert: 'keyboard.ins',
    delete: 'keyboard.del',
    backspace: 'keyboard.backspace',
    //鼠标
    wheelup: 'mouse.wheel_up',
    wheeldown: 'mouse.wheel_down',
    mouseleft: 'mouse.button_left',
    mouseright: 'mouse.button_right',
    mousemiddle: 'mouse.button_middle'
}

module.exports = keys

